#include <algorithm>
#include <boost/multiprecision/cpp_int.hpp>
#include <boost/rational.hpp>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
using boost::multiprecision::cpp_int; using Rational=boost::rational<cpp_int>; using u128=unsigned __int128; using u64=uint64_t;
struct Err:std::runtime_error{using std::runtime_error::runtime_error;};
std::string dec(u128 x){if(!x)return"0";std::string s;while(x){s.push_back(char('0'+unsigned(x%10)));x/=10;}std::reverse(s.begin(),s.end());return s;}
u128 p128(const std::string&s){u128 x=0;for(char c:s){if(c<'0'||c>'9')throw Err("bad u128");u128 old=x;x=x*10+unsigned(c-'0');if(x<old)throw Err("u128 overflow");}return x;}
int cr(const Rational&x){cpp_int q=x.numerator()/x.denominator();if(x.numerator()%x.denominator()!=0&&x.numerator()>0)++q;return q.convert_to<int>();}
std::pair<Rational,Rational> lp(int a,int b,int N){Rational z(cpp_int(a-b),cpp_int(a+b)),z2=z*z,p=z,s(0);for(int j=0;j<N;j++){s+=p/Rational(2*j+1);p*=z2;}Rational lo=2*s;return{lo,lo+2*p/(Rational(2*N+1)*(Rational(1)-z2))};}
std::pair<int,int> pars(int n){int e=0;while((1LL<<(e+1))<=n)e++;int sc=1<<e;for(int N:{8,12,16,24,32,48,64,96}){auto a=lp(2,1,N),b=lp(n,sc,N);Rational lo=Rational(e)*a.first+b.first,hi=Rational(e)*a.second+b.second;int r1=cr(4*lo),r2=cr(4*hi),m1=cr(16*lo*lo),m2=cr(16*hi*hi);if(r1==r2&&m1==m2)return{r1,m1};}throw Err("params");}
std::vector<int> ps(int n){std::vector<bool>a(n+1,true);a[0]=a[1]=false;std::vector<int>p;for(int i=2;i<=n;i++)if(a[i]){p.push_back(i);if(1LL*i*i<=n)for(int j=i*i;j<=n;j+=i)a[j]=false;}return p;}
int vp(int n,int p){int s=0;while(n){n/=p;s+=n;}return s;} cpp_int fac(int n){cpp_int x=1;for(int i=2;i<=n;i++)x*=i;return x;} cpp_int isq(const cpp_int&v){cpp_int l=0,h=cpp_int(1)<<((boost::multiprecision::msb(v)+2)/2+1);while(l+1<h){cpp_int m=(l+h)/2;if(m*m<=v)l=m;else h=m;}return l;}
struct PE{int p,e;u64 c;};
void gen(const std::vector<PE>&f,int i,u128 x,u128 lim,std::vector<u128>&out){if(i==(int)f.size()){out.push_back(x);return;}u128 cur=x;for(int k=0;k<=f[i].e;k++){gen(f,i+1,cur,lim,out);if(k<f[i].e){unsigned p=unsigned(f[i].p);if(cur>lim/p)break;cur*=p;}}}
struct CacheHeader{u64 magic,n,mask,asz,bsz,total;};
int main(int argc,char**argv){try{
 if(argc<3||argc>4)throw Err("usage: checkpoint n mask [chunk_divisors]"); int n=std::stoi(argv[1]);u64 mask=std::stoull(argv[2]);u64 chunk=argc==4?std::stoull(argv[3]):0;
 auto[r,M]=pars(n);int v2=vp(n,2);std::vector<PE>f;u64 total=1;for(int p:ps(n)){if(p==2)continue;int e=vp(n,p)-(p==3);if(e>0){f.push_back({p,e,u64(e+1)});total*=u64(e+1);}}
 if(f.size()>=64||mask>=(1ULL<<f.size()))throw Err("mask range");cpp_int Yb=isq(fac(n))/3;std::string ys=Yb.convert_to<std::string>();if(ys.size()>38)throw Err("Y too large");u128 Y=p128(ys),W=((u128(1)<<r)-3)/3;
 u64 besta=1;for(size_t i=0;i<f.size();i++)if(mask>>i&1)besta*=f[i].c;u64 bestb=total/besta;std::vector<PE>fa,fb;for(size_t i=0;i<f.size();i++)((mask>>i)&1?fa:fb).push_back(f[i]);
 const char* state_env=std::getenv("NOVA_MITM_STATE_DIR");std::string state_dir=state_env?state_env:"/tmp";if(!state_dir.empty()&&state_dir.back()!='/')state_dir+='/';std::string base=state_dir+"nova_mitm_safe_n"+std::to_string(n)+"_mask"+std::to_string(mask),cache=base+".bin",ckpt=base+".ckpt";std::vector<u128>A,B;
 {std::ifstream in(cache,std::ios::binary);if(in){CacheHeader h{};in.read((char*)&h,sizeof(h));if(!in||h.magic!=0x534146454d49544dULL||h.n!=(u64)n||h.mask!=mask||h.total!=total)throw Err("bad cache header");A.resize(h.asz);B.resize(h.bsz);in.read((char*)A.data(),A.size()*sizeof(u128));in.read((char*)B.data(),B.size()*sizeof(u128));if(!in)throw Err("short cache");std::cerr<<"cache=loaded\n";}else{A.reserve(besta);B.reserve(bestb);gen(fa,0,1,Y,A);gen(fb,0,1,Y,B);std::sort(A.begin(),A.end());std::sort(B.begin(),B.end());if(A.size()>B.size())std::swap(A,B);CacheHeader h{0x534146454d49544dULL,(u64)n,mask,(u64)A.size(),(u64)B.size(),total};std::ofstream out(cache,std::ios::binary);out.write((char*)&h,sizeof(h));out.write((char*)A.data(),A.size()*sizeof(u128));out.write((char*)B.data(),B.size()*sizeof(u128));if(!out)throw Err("cache write");std::cerr<<"cache=created\n";}}
 if(A.empty()||B.empty())throw Err("empty truncated half");if(!std::is_sorted(A.begin(),A.end())||!std::is_sorted(B.begin(),B.end()))throw Err("unsorted cache");if(std::adjacent_find(A.begin(),A.end())!=A.end()||std::adjacent_find(B.begin(),B.end())!=B.end())throw Err("duplicate half");std::cerr<<"split="<<A.size()<<"x"<<B.size()<<" total="<<total<<"\n";
 std::vector<uint32_t> heap;std::vector<uint32_t> col(A.size(),0);std::vector<u128>cur(A.size());u128 E=0,prev=0;u64 count=0,start_count=0;int t=1;cpp_int cprod=1;std::vector<std::string>rows;
 {std::ifstream in(ckpt);if(in){std::string line;u64 active=0;while(std::getline(in,line)){auto pos=line.find('=');if(pos==std::string::npos)continue;auto k=line.substr(0,pos),v=line.substr(pos+1);if(k=="E")E=p128(v);else if(k=="prev")prev=p128(v);else if(k=="count")count=std::stoull(v);else if(k=="t")t=std::stoi(v);else if(k=="prod")cprod=cpp_int(v);else if(k=="row")rows.push_back(v);else if(k=="active")active=std::stoull(v);else if(k=="h"){auto c=v.find(',');uint32_t rr=std::stoul(v.substr(0,c)),cc=std::stoul(v.substr(c+1));if(rr>=A.size()||cc>=B.size())throw Err("bad checkpoint heap");col[rr]=cc;cur[rr]=A[rr]*B[cc];heap.push_back(rr);}}if(heap.size()!=active)throw Err("active mismatch");start_count=count;std::cerr<<"checkpoint=loaded count="<<count<<" layer="<<t<<"\n";}else{for(uint32_t i=0;i<A.size();i++){cur[i]=A[i]*B[0];if(cur[i]<=Y)heap.push_back(i);}std::cerr<<"checkpoint=new\n";}}
 auto lessrow=[&](uint32_t x,uint32_t y){return cur[x]<cur[y]||(cur[x]==cur[y]&&x<y);};auto heapify=[&](){for(int i=int(heap.size())/2-1;i>=0;i--){size_t p=i;while(true){size_t l=2*p+1;if(l>=heap.size())break;size_t rr=l+1,c=(rr<heap.size()&&lessrow(heap[rr],heap[l]))?rr:l;if(!lessrow(heap[c],heap[p]))break;std::swap(heap[c],heap[p]);p=c;}}};heapify();
 auto save=[&](){std::ofstream out(ckpt+".tmp");out<<"E="<<dec(E)<<"\nprev="<<dec(prev)<<"\ncount="<<count<<"\nt="<<t<<"\nprod="<<cprod<<"\n";for(auto&s:rows)out<<"row="<<s<<"\n";out<<"active="<<heap.size()<<"\n";for(auto rr:heap)out<<"h="<<rr<<","<<col[rr]<<"\n";out.close();std::remove(ckpt.c_str());if(std::rename((ckpt+".tmp").c_str(),ckpt.c_str())!=0)throw Err("checkpoint rename");};
 u128 scale=u128(1)<<(t-1),D=(E+W+1)/scale,bound=Y/scale;auto resolve=[&](bool blocked,u128 left,u64 K,u128 right,u128 gap){u128 umax=left;E+=scale*umax;cprod*=cpp_int(K)+1;std::string row="layer="+std::to_string(t)+",scale="+dec(scale)+",core_bound="+dec(bound)+",gap_threshold="+dec(D)+",connected_max_core="+dec(umax)+",connected_count="+std::to_string(K)+",carrier_endpoint="+dec(E);if(blocked)row+=",first_blocking_left="+dec(left)+",first_blocking_right="+dec(right)+",first_blocking_gap="+dec(gap);else row+=",first_blocking_gap=NONE";rows.push_back(row);};
 while(true){if(heap.empty()){resolve(false,prev,count,0,0);break;}uint32_t root=heap[0];u128 d=cur[root];if(d>bound){resolve(false,prev,count,0,0);if(E+W<Y)throw Err("no-block continuation");break;}if(d<=prev)throw Err("non-increasing");u128 gap=d-prev;bool ree=true;while(ree&&gap>D){resolve(true,prev,count,d,gap);if(E+W>=Y){ree=false;break;}t++;scale=u128(1)<<(t-1);bound=Y/scale;D=(E+W+1)/scale;if(d>bound)throw Err("next bound passed");}
  if(E+W>=Y)break;prev=d;count++;uint32_t nc=col[root]+1;if(nc<B.size()&&A[root]<=Y/B[nc]){col[root]=nc;cur[root]=A[root]*B[nc];}else{heap[0]=heap.back();heap.pop_back();}if(!heap.empty()){size_t p=0;while(true){size_t l=2*p+1;if(l>=heap.size())break;size_t rr=l+1,c=(rr<heap.size()&&lessrow(heap[rr],heap[l]))?rr:l;if(!lessrow(heap[c],heap[p]))break;std::swap(heap[c],heap[p]);p=c;}}
  if(count%10000000ULL==0){save();std::cerr<<"progress="<<count<<",heap="<<heap.size()<<",layer="<<t<<"\n";}if(chunk&&count-start_count>=chunk){save();std::cout<<"result_class=resource checkpoint\ncount="<<count<<"\nlayer="<<t<<"\n";return 3;}
 }
 std::remove(ckpt.c_str());u128 occ=E+W;cpp_int req=(Yb+cpp_int(W)+1)/(cpp_int(W)+1),ratio=cprod/req;std::cout<<"schema=nova1.marker-three-mitm-overflow-safe-checkpoint-u128.v1\nresult_class=finite certificate\nn="<<n<<"\nr="<<r<<"\nM="<<M<<"\nv2_factorial="<<v2<<"\nY="<<dec(Y)<<"\nW="<<dec(W)<<"\ntotal_odd_core_divisor_count="<<total<<"\nmitm_partition_mask="<<mask<<"\nmitm_rows="<<A.size()<<"\nmitm_columns="<<B.size()<<"\nemitted_until_certificate="<<count<<"\nmaximum_heap="<<A.size()<<"\n";for(auto&s:rows)std::cout<<s<<"\n";std::cout<<"layers_used="<<rows.size()<<"\ncarrier_endpoint="<<dec(E)<<"\noccupied_through="<<dec(occ)<<"\nmargin="<<(occ>=Y?dec(occ-Y):std::string("-")+dec(Y-occ))<<"\nreaches_full_endpoint="<<(occ>=Y?"true":"false")<<"\nterm_bound="<<r+rows.size()<<"\nconnected_prefix_product="<<cprod<<"\nfinite_requirement_ceiling="<<req<<"\nproduct_floor_ratio="<<ratio<<"\n";return occ>=Y?0:2;
 }catch(std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
